# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jump_buy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_jump_buy(object):
    def setupUi(self, Dialog_jump_buy):
        Dialog_jump_buy.setObjectName("Dialog_jump_buy")
        Dialog_jump_buy.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("flight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_jump_buy.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_jump_buy)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.com_class = QtWidgets.QComboBox(Dialog_jump_buy)
        self.com_class.setObjectName("com_class")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.horizontalLayout.addWidget(self.com_class)
        self.label_5 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.remain_num = QtWidgets.QLabel(Dialog_jump_buy)
        self.remain_num.setAlignment(QtCore.Qt.AlignCenter)
        self.remain_num.setObjectName("remain_num")
        self.horizontalLayout.addWidget(self.remain_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sex = QtWidgets.QComboBox(Dialog_jump_buy)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.horizontalLayout_4.addWidget(self.sex)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.combo_kind = QtWidgets.QComboBox(Dialog_jump_buy)
        self.combo_kind.setObjectName("combo_kind")
        self.combo_kind.addItem("")
        self.combo_kind.addItem("")
        self.combo_kind.addItem("")
        self.combo_kind.addItem("")
        self.combo_kind.addItem("")
        self.horizontalLayout_6.addWidget(self.combo_kind)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.name = QtWidgets.QLineEdit(Dialog_jump_buy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.horizontalLayout_5.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.identity_num = QtWidgets.QLineEdit(Dialog_jump_buy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identity_num.sizePolicy().hasHeightForWidth())
        self.identity_num.setSizePolicy(sizePolicy)
        self.identity_num.setObjectName("identity_num")
        self.horizontalLayout_3.addWidget(self.identity_num)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog_jump_buy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.phone_num3 = QtWidgets.QLineEdit(Dialog_jump_buy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_num3.sizePolicy().hasHeightForWidth())
        self.phone_num3.setSizePolicy(sizePolicy)
        self.phone_num3.setObjectName("phone_num3")
        self.horizontalLayout_2.addWidget(self.phone_num3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(Dialog_jump_buy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_jump_buy)
        QtCore.QMetaObject.connectSlotsByName(Dialog_jump_buy)

    def retranslateUi(self, Dialog_jump_buy):
        _translate = QtCore.QCoreApplication.translate
        Dialog_jump_buy.setWindowTitle(_translate("Dialog_jump_buy", "购买机票"))
        self.label_6.setText(_translate("Dialog_jump_buy", "舱位："))
        self.com_class.setItemText(0, _translate("Dialog_jump_buy", "头等舱"))
        self.com_class.setItemText(1, _translate("Dialog_jump_buy", "商务舱"))
        self.com_class.setItemText(2, _translate("Dialog_jump_buy", "经济舱"))
        self.label_5.setText(_translate("Dialog_jump_buy", "剩余票数："))
        self.remain_num.setText(_translate("Dialog_jump_buy", "     "))
        self.label_2.setText(_translate("Dialog_jump_buy", "    性别："))
        self.sex.setItemText(0, _translate("Dialog_jump_buy", "男"))
        self.sex.setItemText(1, _translate("Dialog_jump_buy", "女"))
        self.label_8.setText(_translate("Dialog_jump_buy", "乘客类别："))
        self.combo_kind.setItemText(0, _translate("Dialog_jump_buy", "成人"))
        self.combo_kind.setItemText(1, _translate("Dialog_jump_buy", "小孩"))
        self.combo_kind.setItemText(2, _translate("Dialog_jump_buy", "老人"))
        self.combo_kind.setItemText(3, _translate("Dialog_jump_buy", "病人"))
        self.combo_kind.setItemText(4, _translate("Dialog_jump_buy", "残疾"))
        self.label_7.setText(_translate("Dialog_jump_buy", "乘客姓名："))
        self.label_3.setText(_translate("Dialog_jump_buy", "身份证号："))
        self.label_4.setText(_translate("Dialog_jump_buy", "联系电话"))
        self.pushButton.setText(_translate("Dialog_jump_buy", "购买"))

