# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Administrator_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import re
from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import QSqlTableModel, QSqlQueryModel
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtSql import *
import sys
import register
import login

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(527, 228)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("flight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_flight_no = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_flight_no.sizePolicy().hasHeightForWidth())
        self.label_flight_no.setSizePolicy(sizePolicy)
        self.label_flight_no.setAcceptDrops(False)
        self.label_flight_no.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_no.setObjectName("label_flight_no")
        self.verticalLayout_2.addWidget(self.label_flight_no)
        self.lineEdit_flight_no = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_flight_no.sizePolicy().hasHeightForWidth())
        self.lineEdit_flight_no.setSizePolicy(sizePolicy)
        self.lineEdit_flight_no.setObjectName("lineEdit_flight_no")
        self.verticalLayout_2.addWidget(self.lineEdit_flight_no)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.button_research = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_research.sizePolicy().hasHeightForWidth())
        self.button_research.setSizePolicy(sizePolicy)
        self.button_research.setObjectName("button_research")
        self.verticalLayout.addWidget(self.button_research)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.tableView_search = QtWidgets.QTableView(Dialog)
        self.tableView_search.setObjectName("tableView_search")
        self.horizontalLayout_2.addWidget(self.tableView_search)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.button_research.clicked.connect(self.ad_search)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "管理员查询界面"))
        self.label_flight_no.setText(_translate("Dialog", "航程号："))
        self.button_research.setText(_translate("Dialog", "查询"))

    #复制需要查看的航程乘客信息
    def table_copy(self):
        flight_no = self.lineEdit_flight_no.text()
        query_copy = QSqlQuery()  # 新建sql对象
        query_copy.prepare('SELECT * INTO 隐私查询 FROM 订票 '
                      'WHERE 航程号 = :flight_no')  # 输入SQL语句
        query_copy.bindValue(":flight_no", flight_no)  # 绑定占位符和相应的功能
        query_copy.exec_()
        #QMessageBox.information(self, "提示", "创建成功!", QMessageBox.Ok)

    #查询后删除所复制1的乘客信息
    def table_delete(self):
        query_delete = QSqlQuery()  # 新建sql对象
        query_delete.prepare('DROP TABLE 隐私查询')  # 输入SQL语句
        query_delete.exec_()
        # QMessageBox.information(self, "提示", "创建成功!", QMessageBox.Ok)

    #对于关键信息身份证号进行遮蔽
    def hide_search(self):
        query_hide = QSqlQuery()  # 新建sql对象
        query_hide.prepare("UPDATE 隐私查询 SET[乘客身份证号/护照号] = left([乘客身份证号/护照号], 6) + '********' + substring([乘客身份证号/护照号], 15, 18)")
        # 输入SQL语句
        query_hide.exec_()

    #差分隐私privacy difference指数机制保护用户类型信息
    #可用性函数敏感度为1，隐私预算设定为0.1 e值取2.71828
    def pd_search(self):
        query_pd = QSqlQuery()  # 新建sql对象
        query_pd.exec("EXEC pd_search")


    def ad_search(self):
        flight_no = self.lineEdit_flight_no.text()  # 设置航程号
        if flight_no == '':
            if not self.model.select():
                QtWidgets.QMessageBox.warning(self, "提示", "%s" % (self.model.lastError().text()),
                                              QtWidgets.QMessageBox.Ok)

        self.table_copy()#复制所需查询数据
        self.hide_search()#隐藏身份证号
        self.pd_search()#差分隐私保护用户类型信息

        self.model = QtSql.QSqlTableModel()
        self.model.setEditStrategy(QtSql.QSqlTableModel.OnManualSubmit)
        self.tableView_search.setModel(self.model)  # 绑定table
        self.model.setTable("隐私查询")


        self.model.setFilter("航程号 = %s" % (flight_no))
        if not self.model.select():
            QtWidgets.QMessageBox.warning(self, "提示", "%s" % (self.model.lastError().text()),
                                            QtWidgets.QMessageBox.Ok)
        self.tableView_search.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        if self.model.rowCount() == 0:
            QtWidgets.QMessageBox.information(self, "提示", "未找到符合条件的航程，请重试。", QtWidgets.QMessageBox.Ok)
        else:
            self.tableView_search.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
            self.tableView_search.show()
        self.table_delete()



class Administrator_search_Window(QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super(Administrator_search_Window, self).__init__(parent)
        self.setupUi(self)





