# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtSql import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1000, 1000)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(982, 265))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.user_name = QtWidgets.QLineEdit(Dialog)
        self.user_name.setMaxLength(20)
        self.user_name.setObjectName("user_name")
        self.verticalLayout.addWidget(self.user_name)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(982, 287))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setText("")
        self.password.setMaxLength(20)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setObjectName("cancel")
        self.verticalLayout.addWidget(self.cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.login.clicked.connect(self.login_check)
        self.user_name.returnPressed.connect(self.login_check)
        self.password.returnPressed.connect(self.login_check)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "机票订购系统登录"))
        self.label_2.setText(_translate("Dialog", "用户名"))
        self.user_name.setPlaceholderText(_translate("Dialog", "请输入用户名"))
        self.label_3.setText(_translate("Dialog", "密码"))
        self.password.setPlaceholderText(_translate("Dialog", "请输入密码"))
        self.login.setText(_translate("Dialog", "登录"))
        self.cancel.setText(_translate("Dialog", "取消"))

    def login_check(self):
        user_name = self.user_name.text()
        password = self.password.text()
        if (user_name == "" or password == ""):
            print(QMessageBox.warning(self, "警告", "用户名和密码不可为空!", QMessageBox.Yes))
            return
        # 进行数据库操作
        query = QSqlQuery()#新建sql对象
        query.prepare('SELECT * FROM 用户表 '
                      'WHERE 用户名  = :user_name')  # 输入SQL语句
        query.bindValue(":user_name", user_name) # 绑定占位符和相应的功能
        query.exec_()

        if (not query.next()):
            print(QMessageBox.information(self, "提示", "该账号不存在!", QMessageBox.Yes))
        else:
            if (user_name == query.value(0) and password == query.value(1)):

                if (query.value(2) == 1):
                #跳转到后续管理员窗口
                    print(QMessageBox.information(self, "提示", "登录成功!", QMessageBox.Yes))
                #跳转到后续用户窗口
                else:
                    print(QMessageBox.information(self, "提示", "登录成功!", QMessageBox.Yes))


            else:
                print(QMessageBox.information(self, "提示", "密码错误!", QMessageBox.Yes))
        return
#添加后续窗口